### ISSUE TITLE
Minor contradiction in README.md architecture section

### ISSUE THREAD

**Issue by dmandalidis** [ifad/clammit#11]
In [README.md - Architecture](https://github.com/ifad/clammit/blob/master/README.md#architecture) you mention that only multipart/form-data is supported which somehow contradicts with both the introductory phrase (_Clammit is a proxy that will perform virus scans of files uploaded via http requests, including multipart/form-data_) and the codebase.

**Comment by vjt** [comment]
Thanks for spotting the leftover. Clammit indeed supports both. Patches welcome. :-)

**Comment by dmandalidis** [comment]
@vjt no prob, sorry for the multi-push, I 'm done pushing now :)
