### ISSUE TITLE
Documentation on setup in nginx is very sparse

### ISSUE THREAD

**Issue by Helios-23** [ifad/clammit#16]
working on setting this up to work with our app that uses flask/uwsgi, the location config is particularly causing issues:
not sure what to configure for the following 2 lines

for starters we plan to use a location like so:

  location /api/~ ^(/[^/]+) {
  ...
  }
will this successfully monitor any post calls to /api/all-subdirectories

  #  proxy_set_header X-Clammit-Backend unix:$my_app/.unicorn.sock;
This line seems critically important, but what should the setting point to?

  #  proxy_pass http://unix:$clammit_app/.unicorn.sock;
also critically important. should this point to the location of the clammit unix.sock?
i.e /var/run/.clammit.sock ?

is there any additional documentation on how to configure clammit in nginx? 
any help on this would be greatly appreciated

**Comment by vjt** [comment]
Dear @Helios-23,

I am sorry for the delay in handling this. The README was indeed unclear and now it has been fixed.

Thanks for reporting this.
