### ISSUE TITLE
Check content body for all request types, not only for POST, PUT, PATCH

### ISSUE THREAD

**Issue by maxsivkov** [ifad/clammit#21]
Hello!

Because of [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.3)

> The presence of a message body in a request is signaled by a
   Content-Length or Transfer-Encoding header field.  Request message
   framing is independent of method semantics, even if the method does
   not define any use for a message body.

I think clammit should perform virus checks for all method types, not only for  [POST, PUT, PATCH](https://github.com/ifad/clammit/blob/899519ec0e6c193770f750ff3aeb0e00e81c9770/scan_interceptor.go#L37). 

This could be easily implemented by removing POST, PUT, PATCH checks and just comparing Content-Length and/or actual body size to 0.

**Comment by vjt** [comment]
Makes sense, thank you, will do.

**Comment by vjt** [comment]
Hi,

[v0.7.2](https://github.com/ifad/clammit/releases/tag/v0.7.2) fixes this. Please test and let me know if any issue.

Cheers
