### ISSUE TITLE
Determine clammit health

### ISSUE THREAD

**Issue by ITler** [ifad/clammit#23]
Hello,

as I would like to run clammit in a kubernetes environment, I am wondering how to determine liveness and readiness.
I have seen in the `main.go` that there already is a handler implemented for graceful shutdown which is great IMO.
Once entered graceful shutdown, clammit could communicate being not ready for new connections anymore via a `/readyz` endpoint to let kubernetes not send traffic to the clammit pod anymore.
Not sure to if a dedicated liveness check and endpoint would be needed.

**Comment by vjt** [comment]
Hi,

would a /sys/healthcheck endpoint that returns 200 OK if all looks good and a 503 if anything is wrong suit your purposes? With anythinf wrong I mean failed startup checks, inability to communicate with clamd, etc.

If yes, it can be implemented easily.

**Comment by ITler** [comment]
> If I understood correctly, /readyz indicates whether new traffic should be sent to the instance, so this endpoint would return a 200 OK unless we are gracefully shutting down

Yes I would say so

> whereas the /livez endpoint indicates 

Well, you could omit the live check if you don't really need it (like u don't have a main thread that would monitor worker threads)

> [...] understand this makes sense when clamd is monitored separately, however I don't see that solution fully reliable, as it can happen that the monitor can be able contact clamd, whereas clammit for whatever reason may not be able to contact it [...]

Your thoughts are in general not wrong, but from an operational perspective it is not 'your job' (as the dev and operator of clammit) to consider monitoring `clamd`. The point is that `clamd` will/should be monitored, seperately, (i.e. by [this](https://github.com/r3kzi/clamav-prometheus-exporter)).
Checking if `clammit` would be able to reach `clamd` would be convered by a kind of (automated) integration test before releasing == **deploying** on production, but this depends on how a cloud engineer would set up the whole system. This is not your focus as clammit maintainer.

Maybe another take on it: imagine we run clammit and clamd and the latter would fail. An Ops guy will get a SMS (usually in the middle of a night). Having clammit to also fail (restart) because clamd failed would most likely also produce an alert, but this would not indicate the real problem (which is clamd is failing)... Now imagine complex structures with hundreds of services and dependencies. The Ops guy will get hundreds of alerts in his monitoring dashboards but does not really see the root cause on first glance. This checking dependencies might not be an issue with 2 services, but it will be at scale. That's why I am convinced that it should not be done. Again, only focus on your app.

**Comment by vjt** [comment]
Hi, thanks for taking the time to explain. Maybe one day I'll explore an infrastructure at scale.

I've released [0.7.1](https://github.com/ifad/clammit/releases/tag/v0.7.1) that adds `/clammit/readyz` implementing what we discussed.  Please let me know if it's good for your use case.

**Comment by ITler** [comment]
This is awesome. Thank you. I will test this out as soon as I can.

**Comment by vjt** [comment]
Great! Please note that I have also released 0.7.2 that contains this fix plus the enhancement described in #21. Closing for now, please re-open if anything is wrong with the `healthz` check.
